# Generated by Django 2.2.22 on 2021-05-15 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='TimeStamp'),
            preserve_default=False,
        ),
    ]
